

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR

server:
  port: 8556

spring:
  datasource:
    url:  jdbc:h2:file:./court
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
